import { IRooms } from './interfaces';

export const rooms: IRooms = {
	private: [
		{
			name: 'Private Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
			],
			startBet: 5,
			playersLength: 3,
			playersLengthMax: 11,
		},
	],
	public: [
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'yellow' },
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'blue' },
			],
			startBet: 5,
			playersLength: 11,
			playersLengthMax: 11,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room Free the top one the web',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
		{
			name: 'Test Room',
			players: [
				{ name: 'Player123', avatar: 'red' },
				{ name: 'Player123', avatar: 'blue' },
				{ name: 'Player123', avatar: 'orange' },
				{ name: 'Player123', avatar: 'violet' },
				{ name: 'Player123', avatar: '#545352' },
				{ name: 'Player123', avatar: 'yellow' },
			],
			startBet: 5,
			playersLength: 6,
			playersLengthMax: 8,
		},
	],
};

